### PR TITLE
All commander macros are restricted to commander

### PR DESCRIPTION
**Pull request by flibbles**
Currently, TW-Commander injects 68 macros into the global macro namespace. And as far as I can tell, none of these are macros the end user will ever use. (Please correct me if I'm mistaken).

Every global macro has an overhead. This is something I've [been trying to address in Tiddlywiki](https://github.com/Jermolene/TiddlyWiki5/pull/4108). Each increases stack depth and runtime. Also, they make widgets like `<<dumpvariables>>` all that much harder to use. On top of that, collision is quite possible, especially for some macros, like `display` or `showTags` or `set-title`. If the user uses the names of any of the 68 macros defined in Commander, they're guaranteed either to be breaking Commander, or their own tiddlers.

So I have this PR. Instead of using `$:/tags/Macro` everywhere, commander could use `$:/tags/Commander/Macro` and just use import pragma where necessary. I've done it. I've tested it, mostly. Should help keep Commander's affect on Tiddlywiki more minimal.

### CODE REVIEW

**Comment by kookma** [comment]
@flibbles 
This is what I discussed several time in forum! I also asked for private macro or submacro for example if a macro name is __name then it will not be treated as global or in a tiddler the first macro as global and the below ones as private

By the way thank you for this solution! Now I expect to have a quicker operation!

**Comment by kookma** [comment]
Seems there is a conflict!

**Comment by flibbles** [comment]
Should be ready to merge now.

I built both my PRs off of master, so there was just a touch of overlap.

**Comment by kookma** [comment]
@flibbles 
It is done now!

**Pull request merged**
